version: '2'
services:
  web:
    build: src
    environment:
      - "TZ=Asia/Shanghai"
    volumes:
      - ./sockets:/sockets

  server:
    build: server 
    restart: always
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./sockets:/sockets
      - ./server:/cert
      - ./video:/app/video
