version: '2'
services:
  web:
    build: src
    volumes:
      - ./sockets:/sockets

  server:
    build: server 
    restart: always
    ports:
      - 80:80
    volumes:
      - ./sockets:/sockets
